### ISSUE TITLE
Can't disable modules

### ISSUE THREAD

**Issue by krysennn** [Contentify/Contentify#101]
Hi,

I try to disable some modules but it's not working.

Example with module News:

1.  I edit module.json, and change **enabled: true** by **enabled: false**.
2. I remove modules.json in storage folder.
3. Refresh page and /news working ... and in modules.json it's write: News: true

I think it's Caffeinated problem,

Line [297-299] in LocalRepository.php (/vendor/caffeinated/modules/src/Repositories/)

`
foreach ($modules as $module) {
    $content[$module['slug']] = true;
}
`

For fix:
`
foreach ($modules as $module) {
    $content[$module['slug']] = $module['enabled'];
}
`

But it's vendor so it's not properly right fix :(

Are you an idea ?

Thanks,
Alexis

**Comment by chriskonnertz** [comment]
Hi,

okay, Let's assume that this line causes the issue.
I've run `php composer.phar update` to update the vendor libaries (see https://github.com/Contentify/Contentify/commit/d6e32a63f5c5b46f12af48b394bd6ff3851cae6e ), but there was no update for Caffeinated
.
In the `composer.json` the version for Caffeinated is set to `~2.0`. This seems to be a problem, because the current version is 4.x. For example, this is the release for 3.0: https://github.com/caffeinated/modules/releases/tag/v3.0
Changes have been made since 2.x that require some changes to Contentify. I will try to make the update at the weekend. I hope that this will fix the issue.

**Comment by krysennn** [comment]
It's not urgent but thank you very much 👍

**Comment by chriskonnertz** [comment]
Upgraded caffeinated/modules from v2.2.4 to v3.2.5 and it does seem to work.
However, after upgrading I had to run this console command: `php artisan module:optimize`
This removes `storage/app/modules.json` and recreates it by joining the content of all the `module.json` files from the modules. I'm not yet sure how this affects Contentify.

**Comment by chriskonnertz** [comment]
Commited the changes. https://github.com/Contentify/Contentify/commit/acf5da5d1c35e4d1f13f1a252f768e70b5e967a1

Note: Removed the "enabled" property from the `module.json` files. The release notes say I have to:

> No longer need to add the enabled key to your module manifest files. Please remove these from your manifest files!

https://github.com/caffeinated/modules/releases/tag/v3.0

**Comment by chriskonnertz** [comment]
Todo: I have to test if the installer has to run the `php artisan module:optimize` command at the end of an installation.

**Comment by krysennn** [comment]
It's ok ? Because if its ok i will tell to @mazmol1 how to enable/disable module with artisan command 

https://github.com/Contentify/Contentify/issues/117

**Comment by chriskonnertz** [comment]
I believe it is. :)
