### ISSUE TITLE
[Enhancement] Bracket View

### ISSUE THREAD

**Issue by acamilleri** [Contentify/Contentify#105]
Hello @chriskonnertz,

I make this issue because for my project i changed your braquet view with jQuery Bracket of "teijo".
https://github.com/teijo/jquery-bracket

So i prefer to prevent before other people work on the same ;)

I will make pull requests ASAP.

**Comment by krysennn** [comment]
Hi @chriskonnertz,

I think i finished, i waiting your merge for Snow feature because if i make new pull request i will commit snow feature and bracket feature on the same pull request 👎 I think i'm not good with git ^^

Bracket feature is Jquery Bracket by Teijo -> https://github.com/teijo/jquery-bracket.
i edit for make responsive bracket and i added tooltip (when you mouseover match you will get detail of them).

![image](https://cloud.githubusercontent.com/assets/7473485/21466910/3a56116e-c9d9-11e6-8ec9-2ac6c0e21a4c.png)

**Comment by krysennn** [comment]
https://github.com/Contentify/Contentify/pull/118

**Comment by MohsinAhmedShaikh** [comment]
Where is bracket feature in contentify 2.1 ?

**Comment by chriskonnertz** [comment]
Hi,

well the feature that krysennn has implemented is not yet in the v.21 branch, because it is not yet ready.

However, the _module_ is located here: https://github.com/Contentify/Contentify/tree/2.1/app/Modules/Cups
