### ISSUE TITLE
(IDEA)Updating contentify

### ISSUE THREAD

**Issue by mazmol1** [Contentify/Contentify#116]
A easy Built in way to update the CMS quicker without re downloading a reconfigure it

**Comment by chriskonnertz** [comment]
Your wish is our command! :wink: 

A very stupid and ugly updater has been added right now:
https://github.com/Contentify/Contentify/tree/2.0-dev/app/Modules/Update

It's purpose is to allow to update from version 2.0 to 2.1 when 2.1 is released. The updater ist not very smart and I did not test it very much because there was not enough time. So do not expect too much. In the future we hopefully will get something better.

**Comment by mazmol1** [comment]
Thanks Buddy :D Your Amazing Came across this project looking for one like this your a star :)

**Comment by chriskonnertz** [comment]
Thanks!
