### ISSUE TITLE
Some issues (Search and Pagination)

### ISSUE THREAD

**Issue by schikunow** [Contentify/Contentify#121]
How can i change the Label for the Searchbar and how can i get a pagination on my news site? Now its limited to 5 news.

**Comment by chriskonnertz** [comment]
Hi

>How can i change the Label for the Searchbar

This is the template that contains the search bar: https://github.com/Contentify/Contentify/blob/master/resources/views/model_index.blade.php#L13

This is the code that makes the translation: `trans('app.search')`

Change this to a hard-coded string or change the translation:
https://github.com/Contentify/Contentify/blob/master/resources/lang/en/app.php#L95
Changing the translation might affect other pages as well because this is a general translation. So another way would be to create a new translation only used by the search bar.

>  how can i get a pagination on my news site? Now its limited to 5 news.

Line 51 in the news controller: 
https://github.com/Contentify/Contentify/blob/master/app/Modules/News/Http/Controllers/NewsController.php#L51
Change it from 5 to whatever you like, for example 10.

**Comment by chriskonnertz** [comment]
Maybe I did not really understand  what you mean. It would be great if you upload a screenshot of the label. :)

> The change i have done before but i haven't a pagination. This is my problem ...

Hm, the news overview page does not have pagination implemented.

**Comment by chriskonnertz** [comment]
Closed for now. Please comment or create a new issue if you have any questions.

**Comment by abhishek0306-innverse** [comment]
I want to add pagination on my page . Let me know how I can add pagination my view page. I have added 5 as a paginate(5) in news controller but how can i show pagination on my view file. pagination links are not coming in frontend.
