### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by nrRudiak** [Contentify/Contentify#124]
Hi, I am trying to install this CMS for the first time and its proving rather challenging with my limited expertise so hopefully you can help me get it installed and I will be away!

I have gone through the installation process till the point it asks for me to set a super admin user. I have configered the mail.php settings after setting up a mailgun account, but get the following when I enter in super details and click next! :(

https://gyazo.com/695bf18fa5717bd86f73e13ba456fd85

Many thanks and hopefully you can help me.

Site trying to install on is www.nerdrage.pro

**Comment by krysennn** [comment]
Hi @nrRudiak,

I trying to help you, tell me if your dont understand me because i'm french and my english is bad ^^

This is known bug, we work on new installer because we have some problem with actual installer.
So trying this:
Run installer again, when you set database identifier and click next you will get error, trying to return on previous page and click next again

**Comment by nrRudiak** [comment]
Hi @krysennn thanks for your response!

I did try a few times but didn't seem to make a difference. Should I do a fresh install of contentify everytime  I run through the installer? And should I just keep clicking previous page and next again until it works?

**Comment by nrRudiak** [comment]
Wohoo!Managed to get it to work through multiple (10+) attempts! Thanks for your fast help @krysennn !
