### ISSUE TITLE
Steam login problem

### ISSUE THREAD

**Issue by vlaad23** [Contentify/Contentify#125]
Hello,
i had a problem with steam login.
i already put steam api key in config file, but after log in the steam account, this error occurs 

> cURL error 60: SSL certificate problem: unable to get local issuer certificate

what did i do wrong here ?

**Comment by chriskonnertz** [comment]
This does seem to be a problem of the Steam authentication library that we use: https://github.com/invisnik/laravel-steam-auth

Maybe the easiest solution is to disable HTTPS: https://github.com/invisnik/laravel-steam-auth#usage-example I cannot tell you ad hoc how to disable this in Contentify since I don't remember where these settings are stored in Contentify. Maybe you want do take a look on your own? Because I do not know when I will be able to take a deeper insight.

You can also try to do a composer update via console: `php composer.phar update` 
But I do not assume that this will help.

**Comment by chriskonnertz** [comment]
Still had no time to take a closer look at this problem, sorry.

**Comment by acamilleri** [comment]
Hi @vlaad23,

Your website is with HTTPS ? can you add this: 

> 'https' => false

 in your 
> config/steam-auth.php

Like that:
```
return [

    /*
     * Redirect URL after login
     */
    'redirect_url' => '/login',
    /*
     *  API Key (http://steamcommunity.com/dev/apikey)
     */
    'api_key' => 'Your API Key',
    /*
     * Is using https?
     */
    'https' => false
];
```

If it's not working test with 

> 'https' => true

**Comment by acamilleri** [comment]
Hello @vlaad23 it's ok now ?

**Comment by CaptainRafael** [comment]
It doesnt work for me I get another error ErrorException in helpers.php line 747:
Object of class Invisnik\LaravelSteamAuth\SteamInfo could not be converted to string

**Comment by chriskonnertz** [comment]
Okay seems like we have to fix a bug here...

**Comment by psych0path1337** [comment]
@chriskonnertz can you help me with my problem please? [https://github.com/invisnik/laravel-steam-auth/issues/48](url)

**Comment by bitbot-marina** [comment]
I'd like to mention that I'm having a similar issue to what @Corse-eSports is seeing. I've made a few attempts to fix the issue of the _SteamInfo_ not being converted to a string properly, but no luck so far?

By all means, feel free to attempt a login via Steam on my site:
http://107.170.242.209/

**Comment by chriskonnertz** [comment]
Yeah I can see the exception. :(

**Comment by chriskonnertz** [comment]
@psych0path1337 @matt-marek

The steam auth libary made some changes that were not compatible with the code of Contentify.

Bug(s) fixed: https://github.com/Contentify/Contentify/commit/e2ecfb87fe65947bcc649ac94d05e1cc206e554a

**Comment by bitbot-marina** [comment]
Can confirm that the issue has been resolved after applying the bug fix!
