### ISSUE TITLE
Community / forum help

### ISSUE THREAD

**Issue by fabiantomischka** [Contentify/Contentify#134]
Hey Chris!
I saw that you're about to create a community and a forum for all the stuff happening around Contentify. I found no way to contact you privately, though I wanted to let you know I want to participate in any way I can.

We and a few colleagues from the esport community are actively using your CMS which does really hell alot of work. So we want to contribute back if this is possible in any way. :)

**Comment by chriskonnertz** [comment]
Hi Astinox,

> I saw that you're about to create a community and a forum for all the stuff happening around Contentify

Yes, that's the plan but I do not know when this will happen. I guess it will take ~two months or so to realize that. Unfortunately I am extremly busy these days but I hope that this will hange after the upcoming weekend.

>  I found no way to contact you privately

You can write a message to the Contentify account on Facebook / Twitter. Another way is to send an email to one of the email addresses, for example contentifycms [ at ] gmail [ dot ] com.

> So we want to contribute back if this is possible in any way

Well that kinda depends. Is someone of you guys a web developer? Then there are a lot of ways to help. :p Another thing is pretty simple: Just let me know what you dislike about the CMS or what feature you would love to see in the future. This kind of feedback is very important. Don't hesistate to mention everything that you can imagine. It doesn't matter if the outcome is a huge list of criticism. A CMS never is "complete", it never has all the features that its users want to have and it never is 100% up-to-date in comparison to the state of the art of modern content management systems. Especially, because Contentify is a specialsed CMS so it does not have the same giant variety of features that for example Wordpress can offer via plugins.
