### ISSUE TITLE
I can't install Contentify on my website

### ISSUE THREAD

**Issue by CaptainRafael** [Contentify/Contentify#135]
Please check the link bellow , I cant install 
http://corse-esports.tk/v1/public/install?step=4

**Comment by acamilleri** [comment]
Hi,

Your webhosting is not compatible with Contentify.
Error: 
"set_time_limit() has been disabled for security reasons"

For get maximum compatibility with Contentify you need to buy VPS or dedicated server.
You can get this here: digitalocean.com, scaleway.com or ovh.com

**Comment by chriskonnertz** [comment]
@Corse-eSports

Suggestions:

1. Talk to you hoster and ask for help. The problem is the configuration of your server. The server does not allow PHP (and Contentify) to change the PHP setting "max_execution_time". However, most likely your hoster will not change that restriction.
2. Dirty hack: Open `contentify/Controllers/InstallController.php` with a text editor, go to line 291, and delete this command: `set_time_limit(120);` Then the error will not occur again. This *might* lead to problems with the installation but well in my opinion you should give it a try.

_Task for me: Is  there a way to check if PHP has the right tochange the time limit before calling the function?_

**Comment by chriskonnertz** [comment]
Thanks to your feedback @Corse-eSports I added another check if the use of the `set_time_limit()` function is allowed. The installer will only try to call this function if it is allowed to do so.
https://github.com/Contentify/Contentify/commit/1e55c7e8ed0dba54148a5a6d54579b092a3c90c9
