### ISSUE TITLE
Question about instal (root)

### ISSUE THREAD

**Issue by batafly5** [Contentify/Contentify#144]
**Hello all, i have a some questions about this fantastic CMS instal.**

Ok lets go:

1. I upload all files from _contentify2_0_ folder to server _public_html_ folder.
 
2. Next i chmod all files who needet.
 
3. Then i instal this CMS

**QUESTION:**
When i must upload files to receive normal adress: http://myweb.com. Now i recive: http://myweb.com/public ???

**Comment by chriskonnertz** [comment]
Hey,

yes. The cms folder contains a folder called `public`. This is the... well the public folder :p This is the *only* folder that is meant to be accessible from the outside of your server. So what you should do is to configure your server so that it only delivers this folder. You have to configure your application's document / web root to the public directory. Details: stackoverflow.com/questions/5891802/how-do-i-change-the-root-directory-of-an-apache-server#answers-header

**Comment by Erezey** [comment]
Hello, can u give me any your contacts? I have so many questions

**Comment by batafly5** [comment]
If i upload just public folder to public_html i have normal site?

**Comment by batafly5** [comment]
**chriskonnertz** ty man!!!

But just create txt file, then i wtite this:

_RewriteEngine on
RewriteCond %{HTTP_HOST} ^domain-name.com$ [NC,OR]
RewriteCond %{HTTP_HOST} ^www.domain-name.com$
RewriteCond %{REQUEST_URI} !folder/
RewriteRule (.*) /folder/$1 [L]_

In the above lines you should replace the following 2 strings:

domain-name.com - Type your own domain name
folder - Type the name of the sub-folder which has the test/development website

Then upload this .txt file to _public_html_ folder and replace it to _.htaccess_

Now it work!!!

**Comment by chriskonnertz** [comment]
@Erezey Done.

**Comment by chriskonnertz** [comment]
> If i upload just public folder to public_html i get normal site?

Well... no. :p

> Now it work!!!

Great! =)

**Comment by chriskonnertz** [comment]
@batafly5 I copied your hint to the official readme. Thanks again!

=> https://github.com/Contentify/Contentify/wiki/Troubleshooting#installation-what-to-do-with-the-public-folder

(Is everything okay there?)

**Comment by batafly5** [comment]
Yes all ok @chriskonnertz
