### ISSUE TITLE
Hide Blank Profile Fields

### ISSUE THREAD

**Issue by bitbot-marina** [Contentify/Contentify#151]
Is it possible to make it so any profile fields that are "NULL" can be set to hidden?

**Comment by chriskonnertz** [comment]
Well yeah, that is possible. You can try to do that on your own. You have to open this file: `https://github.com/Contentify/Contentify/blob/2.0/app/Modules/Users/Resources/Views/show.blade.php` It containts a table with `<tr>` entries for the different fields. You have to wrap them with a condition, for example:

**Old**:

```
<tr>
    <th class="title">{!! trans('users::birthdate') !!}:</th>
    <td>{{ $user->birthdate }}</td>
</tr>
```

**New**:

```
@if (users::birthdate)
<tr>
    <th class="title">{!! trans('users::birthdate') !!}:</th>
    <td>{{ $user->birthdate }}</td>
</tr>
@endif
```

(Once you have added all the conditions that you need, you should create a backup of the modified file since it might be overwritten by updates in the future.)

**Comment by bitbot-marina** [comment]
Thanks, I've found one small error:

```
@if (users::birthdate)
<tr>
    <th class="title">{!! trans('users::birthdate') !!}:</th>
    <td>{{ $user->birthdate }}</td>
</tr>
@endif
```

Should be:

```
@if (users->birthdate)
<tr>
    <th class="title">{!! trans('users::birthdate') !!}:</th>
    <td>{{ $user->birthdate }}</td>
</tr>
@endif
```

At least, that's what I had to do on my build? 

And yes, I have my own repo for my project and have been updating things manually to avoid breaking anything. 👍

**Comment by chriskonnertz** [comment]
Oh yes, `->` not `::`. :)
