### ISSUE TITLE
News Page Problem

### ISSUE THREAD

**Issue by mix2002** [Contentify/Contentify#157]
Hello i have this problem, i need to put it to Europe/Lisbon. I changed php.ini date to Europe/Lisbon but keep not working :/

![screenshot_2](https://cloud.githubusercontent.com/assets/8055275/24730814/da38f00a-1a5d-11e7-8ca6-4fa7ca70dcf7.png)

**Comment by chriskonnertz** [comment]
Hello,

open `config/app.php` with a text editor. At line 89 (or close to it) I expect this code: `'timezone' => 'UTC'`
Try to change it to your time zone. I don't know it it helps but this idea jsut came to my mind. I guess it overwrites the value in the php.ini. I have also changed the code so that it should display the right value now: https://github.com/Contentify/Contentify/commit/c59fa5859a298c96e83ae8fcc6b6be2eab9c76be
