### ISSUE TITLE
Comments report idea for future

### ISSUE THREAD

**Issue by Edaniel91** [Contentify/Contentify#178]
Hi. First one, this CMS is verry easy and verry nice! Thanks for creating one. Second, i have a nice idea. Now we have forum reports, can we have also comments report in future? And can we have another module like: Website offline, please come back later? In admin CP u can shut down a website for a while. :) Thanks!

**Comment by chriskonnertz** [comment]
Hi,

>  this CMS is verry easy and verry nice! 

Thank you! :)

> Now we have forum reports, can we have also comments report in future?

Yes, that is a very good idea. 

> And can we have another module like:  Website offline, please come back later

We do not have such a module atm, but the CMS/framework has an offline-mode already. This is a feature that comes from the framework that we use, Laravel. You can read more about it here: https://laravel.com/docs/5.2/configuration#maintenance-mode

You have to execute this command via a console / terminal (SSH). 

It is not available via the admin control panel, because well, it would be easy to add the "activate maintenance mode"-button, but not that easy to add a "deactivate maintenance mode"-button, since the log-in and admin CP would not work while the maintenance mode is active.
