### ISSUE TITLE
ErrorException in ProcessUtils.php line 74:

### ISSUE THREAD

**Issue by NapalmEsports** [Contentify/Contentify#188]
We are getting the following error while installing Contentify on a shared host at step 4 in the installation process

## **ErrorException in ProcessUtils.php line 74:
escapeshellarg() has been disabled for security reasons**

Here are some [screenshots](https://www.dropbox.com/sh/omhyr273ooits90/AABZY6ZDPbquYPWDA0xHejTCa?dl=0)

**Comment by chriskonnertz** [comment]
Hello,

this *might* have been fixed in versin 2.1 (still in development state): https://github.com/Contentify/Contentify/tree/2.1-dev

But I do not rebember for sure.

**Comment by chriskonnertz** [comment]
Sorry for the silence.

I have to retract my statement. There is no "bugfix" for the problem.

This is becasue I cannot write a bugfix. The use of escapeshellarg() happens outside of the direct code of Contentify. Contentify uses a lot of third party code (vendor code) such as components from Symfony. You might have heard of Symfony, it is very popular amongst PHP developers. Unfortunately this means that I cannot do much about it since I cannot modify vendor code. Why? Well because if you take a look at your local installation of Contentify and the code here in the repository on Github you will notice that on GitHub there is not `vendor` folder. Vendor code comes from Packagist so I cannot change it. There are workarounds but they come right out of hell. 

Webspace hosters disallow the uses of escapeshellarg() for "security reasons". However,  escapeshellarg() is **not** a dangerous command! If anything it is the opposite, it helps to protect the server at least that is what I understand. I do not know why hosters believe it to be a danger. You might want to try to talk to your hoster about this topic. But to be honest, the answer most likely will be that they cannot do anything about it... Instead I expect them to play the blame game and to call it a security issue and a problem of the code. :(
