### ISSUE TITLE
PDOException in Connector.php line 55:

### ISSUE THREAD

**Issue by NapalmEsports** [Contentify/Contentify#189]
Tried installing the Dev 2.1 version of contentify on shared hosting and got the following error at step 4 of the installation process.

**## PDOException in Connector.php line 55:**
SQLSTATE[HY000] [2002] No such file or directory

here are the screenshots of this [error](https://www.dropbox.com/sh/1fmglw54vsti4yg/AADah3vWfu7PC4VriPKERRoVa?dl=0)

**Comment by chriskonnertz** [comment]
Hi,

as a fast workaround I will figure out how you can fix the issue https://github.com/Contentify/Contentify/issues/188 without having to install v2.1.

**Comment by chriskonnertz** [comment]
I had no luck with a workaround, take a look at my comment on the other issue.

It is difficult to help here. Using shared hosting environments is a challenge for a more advanced web application such as Contentify. This problem is not known to me so all I can do is using Google. :P 

Please take a look at this link: https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory#answer-20733001
