### ISSUE TITLE
Problem with page

### ISSUE THREAD

**Issue by SN4RX** [Contentify/Contentify#208]
Hi, at first I would like to apologize for my English - everything was translated using Google Translate. When on my page in the menu I will select for example: "Partners" and hit back on logo, color # cc3e26 remains on "Partners" and should move to "Home". In addition, the news page is too much on the header, you can see it on the screen: http://imgur.com/mNk7vbP

**Comment by SN4RX** [comment]
What do I do with it?

**Comment by chriskonnertz** [comment]
Hello

>  In addition, the news page is too much on the header

Strictly speaking, that's not a _bug_. I know that it looks odd but the reason is that you did not add any slider items. If you take a look at the demo page http://demo.contentify.org there you can see that between the main navigation and the content section of the page (which includes the news section) there is a slider.

But I agree that it *looks* like a bug.

> When on my page in the menu I will select for example: "Partners" and hit back on logo, color # cc3e26 remains on "Partners" and should move to "Home".

Yes, this is a bug. The CMS uses some JavaScript code to mark the "current" navigation item but it is does not work very well. I'll create a new bug ticket for it.

**Comment by snarxcsgo** [comment]
And how do I get this slider to add?
