### ISSUE TITLE
Problem with Polish characters

### ISSUE THREAD

**Issue by SN4RX** [Contentify/Contentify#225]
Hello, when changing in for example: /app/Modules/Users/Resources/Lang/en

When I want to change Gender to Płeć unfortunately but nothing displays because it does not read Polish characters how to fix it?

Screenshot: https://imgur.com/ctxJg8o

**Comment by SN4RX** [comment]
@chriskonnertz

**Comment by chriskonnertz** [comment]
Hi,

you said you tried to change "Gender" to "Płeć" but on your screenshot I cannot see "Płeć".

But yep I can see the charset problems. But I do not have them:
http://abload.de/img/gender_translationhysm2.jpg

Are you sure that this is a problem that is caused by the CMS? Maybe the editor you used to do the translations has a problem with unicode characters?

**Comment by SN4RX** [comment]
I edited it through Notepad ++

**Comment by chriskonnertz** [comment]
Please upload the `app/Modules/Users/Resources/Lang/pl/main.php` language file so I can take a look at it.

**Comment by SN4RX** [comment]
[main.zip](https://github.com/Contentify/Contentify/files/1300271/main.zip)

**Comment by SN4RX** [comment]
Everything is fixed, just translated that main.php from the downloaded Contentify to my.

**Comment by chriskonnertz** [comment]
Ok.
