### ISSUE TITLE
Vserver installation

### ISSUE THREAD

**Issue by Mrciler** [Contentify/Contentify#239]
I have a vserver from another hoster but i cant install it there or hwo do i install it there ?

**Comment by chriskonnertz** [comment]
Hello,

if you have a VServer this is great, because it should allow you to configure it exactly in a way so that it meets all requirements.

> but i cant install it there

What is the problem? What went wrong?

**Comment by Mrciler** [comment]
i dont realy know how to install it and need a link for vserver installation

Am 10.10.2017 21:09 schrieb "Chris Konnertz" <notifications@github.com>:

**Comment by chriskonnertz** [comment]
Okay, here are some resources:

https://github.com/Contentify/Contentify/issues/58
This is a condensed how-to. It is more meant as an overview than a detailed step-by-step guide.

https://github.com/Contentify/Contentify/wiki/Installation
Wiki chapter about the installation, especially take a look at the "Installation" section: https://github.com/Contentify/Contentify/wiki/Installation#installation

You might also take a look at this script (it is meant to prepare a DigitalOcean.com server/droplet for Contentify) since it contains some important commands:
http://contentify.org/share/install.sh
