### ISSUE TITLE
Sidebar Control

### ISSUE THREAD

**Issue by MtechnikX** [Contentify/Contentify#245]
I would like to take away the side bar from the forums as I would like to have it in full display. I was searching for the codes to delete the sidebar function but I couldnt find it anywhere. Thanks in advance.

**Comment by chriskonnertz** [comment]
Hello,

two ways, one is to disable the sidebar via CSS and resize the rest of the page and here is another way:
1. Open the main template file of the theme you use, for example `app/Modules/PhobosTheme/Resources/Views/layout.blade.php` with a text editor.
2. Remove this: `<aside id="sidebar" class="col-md-4">...</aside>` (and every lines that are inside)
3. Change this `<div id="content" class="col-md-8">` to `<div id="content" class="col-md-12">`

You should note these changes somewhere, because if you update to a newer version of Contentify they might get overwritten.

**Comment by MtechnikX** [comment]
Ok, thanks @chriskonnertz I will give this a try and let you know the out come of it.

**Comment by MtechnikX** [comment]
Thank youl @chriskonnertz this worked for both themes :) Exactly what Im looking for. May there should be in the future to have this as an option on the admin settings/configuration. Again thank you.

**Comment by chriskonnertz** [comment]
Good idea. :)
