### ISSUE TITLE
Nginx Configuration

### ISSUE THREAD

**Issue by JenkinJoe** [Contentify/Contentify#26]
Hello there,
first, thank you for the awesome eSports CMS. I really appreciate it and i'm glad that it works perfectly on apache. However, after moving to Nginx it left me some problems, which in fact i couldn't solve still.

By pointing that, my nginx conf.:
![ss 2015-10-17 at 05 01 57](https://cloud.githubusercontent.com/assets/15172188/10559437/07f312e6-74f1-11e5-85eb-3b038865e666.png)

So as you can see, i tried to adopt your public/.htaccess file. The Major Problem is that somehow i can't open some wildcarts uri's like : news/{id}/{slug?}
You can check this out on the website i recently made : http://corvuspro.de 
Furthermore: http://corvuspro.de/news/12/hgh

**Comment by chriskonnertz** [comment]
Hello,

thank you for your feedback. Unfortunately I have not tested it with nginx.

Most likely this is an issue of the underlying PHP framework, Laravel. Did you search for articles that explain how to install Laravel on nginx? Here is one example (I believe it's about Laravel 4.x while Contentify uses 5.1, however, it may be helpful): https://www.digitalocean.com/community/tutorials/how-to-install-laravel-with-an-nginx-web-server-on-ubuntu-14-04

I suggest to enabled the debug mode of Contentify/Laravel to get a more detailed error message. To do so, open `config/app.php` and set the `debug` value to `true`. if you post the resulting error message here maybe I can provide better help. (Or maybe not since I am not familiar with nginx... )

**Comment by JoeXmt2** [comment]
Thank you, i've solved the Problem.
Permissions have to be granted...

**Comment by JenkinJoe** [comment]
Thank you, i've solved the Problem.
Permissions have to be granted...

**Comment by chriskonnertz** [comment]
Ok, great!
