### ISSUE TITLE
I get: QueryException in Connection.php line 770: when trying to install.

### ISSUE THREAD

**Issue by YourGuyArcher** [Contentify/Contentify#279]
Does anyone know how I can fix this issue?

QueryException in Connection.php line 770:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'temp.countries' doesn't exist (SQL: INSERT INTO countries(title, code, icon, creator_id, updater_id) VALUES
("European Union", "eu", "eu.png", 1, 1),
("Argentina", "ar", "ar.png", 1, 1),
and then more of these countries lol.

anyone know a fix?

**Comment by chriskonnertz** [comment]
Hello,

that's a new one. I have no idea what may cause such an exception. 

Did you try to install it again? Delete all tables, *then* try to install it again? 

The exception says that it cannot add new rows into the "countries" table, because it does not exists. But this table should exist: https://github.com/Contentify/Contentify/blob/2.2/contentify/Controllers/InstallController.php#L346

**Comment by chriskonnertz** [comment]
I close this issue, because there has been no acitivity. If you still need help, please reopen this issue or create a new one.
