### ISSUE TITLE
Support for other databases

### ISSUE THREAD

**Issue by tbe** [Contentify/Contentify#317]
Hi,

as Laravel supports other database types then MySQL/MariaDB, would it possible to support at least PostgreSQL for Contentify?

As a DBA i don't like MySQL for multiple reasons:
- Crash safety
- Syntax
- Missing Optimization Options
- Bad, really bad, Query Planner
- ....

**Comment by chriskonnertz** [comment]
Hello,

uhm... I don't know. Your arguments are reasonable. However, (re-)adding support for Postgre might take a lot of affort. Right now this has not a very high priority.

**Comment by chriskonnertz** [comment]
Hello,

final statement: Yes, you are right demanding support for other DBMS. However, this has a pretty low priority. So this is not a scheduled task. 

If you do not want to use MySQL, there is still MariaDB.

Nevertheless, thank you for the feedback! So now I know there is someone interested in a wider DBMS support.

**Comment by chriskonnertz** [comment]
Hello,

I have to revert my last post.

**Postgre ist supported** - _in theory at least_.

Since I do not use Postgre I cannot give any statement about how good it works in reality but in theory it should work. Ofcourse some feature of the CMS are especially based on MySQL but theses cases *should* be handled so no error should be caused. But again, this is just theory. When using Postgre you should test the website very carefully bevore going live.

**Comment by tbe** [comment]
@chriskonnertz great! I will test this as soon as i have some spare time ;)
