### ISSUE TITLE
Login doesn't work at all

### ISSUE THREAD

**Issue by niclasreich** [Contentify/Contentify#326]
Hi,

when I try to login myself after the installation via /auth/login, the website just reloads, but I am not getting logged in. When I register a new account, it logs me in automatically, but even after logging out I am not able to log myself back in with the new account. Also tried [this (#309)](https://github.com/Contentify/Contentify/issues/309#issuecomment-376264358) fix.

I read in #295, that it could be an error connected to using SSL/HTTPS. Our server only works with https enabled, there is no (easy) way to disable it.

**Comment by niclasreich** [comment]
Managed to fix it by turning on `Automatic HTTPS Rewrites` in Cloudflare, so the form would load fully on HTTPS.

**Comment by chriskonnertz** [comment]
Glad to hear that it works now!

**Comment by niclasreich** [comment]
Yeah, but you definetly need to work on that!

**Comment by chriskonnertz** [comment]
I think the problem was that you did not activate the HTTPS support in the Contentify configuration.
Therefore the CMS tried to force the client to use HTTP.

I removed this piece of code since it did not work the way it should:
https://github.com/Contentify/Contentify/commit/7f4c39187aa608a6630d04281b8099b76a36688c#diff-f8797488503130f478d6934f54f556d9L5
