### ISSUE TITLE
500 Internal Server Error at Installation Step 4

### ISSUE THREAD

**Issue by caglartufan** [Contentify/Contentify#339]
Hello everybody,
Everything is ok on my server without PHP Escapeshellarg function, but when i into go step 4 at database connection, everything fine. When i press button after put the DB infos it gives me back 500 Internal Server Error. Can you help me please?

**Comment by chriskonnertz** [comment]
Hello,

no. :P 

Because we are not able to guess what the actual problem is. "500 Internal server error" just tells us that there was an error when the server tried to do something, but we do not know what error. Mostl likely the server created a log file in the folder `Contentify/storage/logs/`. Take a look at this file, it should contain the error message. Then post it here (but be careful, these message can contain secret data such as the database password! Remove such data before you post here!)

**Comment by caglartufan** [comment]
Only there is one file:
laravel.log
The file URL iş: https://drive.google.com/file/d/1VmJgzRIyFfFX_qs4Mbr0e2-vBqZyULFd/view?usp=drivesdk

**Comment by chriskonnertz** [comment]
Hello,

thanks. In your log file there is this error message:

```
ErrorException: get_cfg_var() has been disabled for security reasons 
```

`get_cfg_var()` is a function of PHP. In my opinion it is not an "evil" function so please let the PHP scripts use it. If your web space is managed by a service provider, please ask their support team to allow this function.
