### ISSUE TITLE
Comments writing, error: Error: Request failed. Code: 400. Message: "Bad Request"

### ISSUE THREAD

**Issue by jonatant** [Contentify/Contentify#373]
Hi again. Previously i got same bug, but my issue is closed with your bugfix. I try to fix like u posted by bugfix. But same problem, cannot create comment. I tryed with empty form and fill it, same thing and same error: Error: Request failed. Code: 400. Message: "Bad Request".

**Comment by chriskonnertz** [comment]
Hello,

please try another browser, it might be just a cache problem.

**Comment by jonatant** [comment]
@chriskonnertz yeah, tried with Chrome and works fine. But why with opera getting error message?

**Comment by chriskonnertz** [comment]
I use Opera as well and it worked with it. Please try Shift+F5 to enforce reloading of all JavaScript files.

**Comment by jonatant** [comment]
Thanks @chriskonnertz SHIFT+F5 fixed that! Love this CMS <3

**Comment by jonatant** [comment]
Another question for u @chriskonnertz i made little update for video module, and now then i'm using search i'm getting error: `Error: Controller "App\Modules\Videos\Http\Controllers\VideosController" does not implement the GlobalSearchInterface. You have to implement this interface if you want this controller to be searchable.` do u know what's wrong? :)

**Comment by andakawa** [comment]
Hi,
I just encountered a similar problem (using 2.4).
When writing comments I get the Server Errror 500 and I was unable to solve this atm.

I currently don't know where to look at in order to try to fix that. Any hints?

**Comment by chriskonnertz** [comment]
@andakawa Did you apply this change to your installation? https://github.com/Contentify/Contentify/commit/c30c4e1df0b97b7c590379425a5fdfed6409dc11

**Comment by andakawa** [comment]
@chriskonnertz Unfortunately not since the cms magically stopped working after one of the admins on our page cleared the cache via the admin backend so I'll have to install the cms again - but this time I can use the fixed release. I'll keep you updated :) But if there's one more big failure I'll have to move to DigitalOcean :D

(the error: every link stopped working, some links on the mainpage gave me the debug-mode error page and others the regular one - debugging was still enabled so I have no idea what caused this)

Edit:
the new package worked - some views still had bad naming (Cat -> cat)
