### ISSUE TITLE
Fix Advertisements No Show Bug

### ISSUE THREAD

**Issue by iktray** [Contentify/Contentify#381]
The Advertisements don't show on the website.

**Comment by chriskonnertz** [comment]
Hello,

- Which version of Contentify do you use?
- Do  you have the lastest version of the main template of the theme you use? Maybe you did some customization and therefore do not have the latest version that includes the advertisement widgets? I mean this template: `app/Modules/<THEME-NAME>/Resources/Views/layout.blade.php`
- Do you use the "Default" category for your advertisements? Because per default the advertisement widget randomly chooses a category that it wants to display so if you have more than one category the ad might not be displayed.

**Comment by kamohy** [comment]
it works in 2.5
