### ISSUE TITLE
Bugs/Features Requests For 2.5 Update!

### ISSUE THREAD

**Issue by iktray** [Contentify/Contentify#382]
**I LOVE CONTENTIFY!!**
Let me know if anything I can do to support.

- Twitch stream bug.
- Position rearrange bug.
- Rest password bug.
- Advertisement no show bug.
- Have the option to remove accounts.
- Fix the files names to lowercase.
- Fix Navigations bug.
- Add description to the site(SEO FRIENDLY).
- New 404/Error page.
- New Forum UI design.
- New messages and friends UI design.
- Possibly a new simple theme.
- Put site in maintenance mode in the admin backend.
- Change favicon and site logo in the admin backend.

**Comment by chriskonnertz** [comment]
Hello,

> I LOVE CONTENTIFY!!

Thanks! :)

Did you find all these bugs in v2.4?

**Comment by iktray** [comment]
Yes.

**Comment by MrFoxyOfficial** [comment]
Hello. 

Any info regarding this bugs?

**Comment by chriskonnertz** [comment]
Nope. Primarily, because I do not know what exactly some of these bugs/ideas are. For instance: `Have the option to remove bugs` I do not understand this one. This option already exists?! Write a fix for the bug, commit it to GitHub, create a pull request and I will merge it...

Others are good proposals that will be implemented in the future, for instance: `Add description to the site(SEO FRIENDLY).`

**Comment by chriskonnertz** [comment]
Closing this. Some of the bugs should have been solved or at least documented somewhere else. Some of the feature ideas have been implemented and others are on my to-do-list.
