### ISSUE TITLE
Contentify Error - NotFoundHttpException in RouteCollection.php line 161:

### ISSUE THREAD

**Issue by RaceTubeGermany** [Contentify/Contentify#385]
Hello guys, i hope you can help me. I install contentify CMS 2.4 and it works fine.
But i have issus at the user registration.

this is the error code:

 1.  in RouteCollection.php line 161
 2.  at RouteCollection->match(object(Request)) in Router.php line 766
 3.  at Router->findRoute(object(Request)) in Router.php line 621
 4.  at Router->dispatchToRoute(object(Request)) in Router.php line 607
 5.  at Router->dispatch(object(Request)) in Kernel.php line 268
 6.   at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
 7.   at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
 8.   at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
 9.  at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
10. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
11. at Pipeline->then(object(Closure)) in Kernel.php line 150
12. at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
13. at Kernel->handle(object(Request)) in index.php line 52

I dont know, what to do?

Did you have some tips?

Page: racetube-germany.de

Thanks a lot

**Comment by chriskonnertz** [comment]
Hello,

please compare your `app/Modules/Auth/Http/web.php` file with https://github.com/Contentify/Contentify/blob/2.4/app/Modules/Auth/Http/web.php . For example you can do this online with this tool: https://www.diffchecker.com/
There should not be any difference. If there is a difference, please copy + paste the code of the linked file, because it is newer and should fix the bug.

**Comment by RaceTubeGermany** [comment]
Thanks a lot.

You are the best !!!!

Solved
