### ISSUE TITLE
Setup Contentify for Development?

### ISSUE THREAD

**Issue by alex809** [Contentify/Contentify#408]
Does anyone have a guide on configuring Contentify for development?

I've installed Laragon, but how does one clone it so you can push / pull updates & be able to view it on your localhost?

Cloning for push / pull so updates can be made & configured so it's possible to view the public script to verify issues are resolved.

A guide on configuring it would be great, I'm not entirely sure how to do it. I've got it cloned so it runs locally but I haven't figured out how to configure it so you can push / pull anything.

Thanks guys

**Comment by chriskonnertz** [comment]
Hello,

> I've got it cloned so it runs locally but I haven't figured out how to configure it so you can push / pull anything.

What is your intention? Why do you want to push something and what would be the target?

Why are you not able to pull? Did you try `git pull`via console or what was your attempt? Or what git client do you use?

**Comment by alex809** [comment]
The intention is to take an approach at learning some PHP while trying to contribute to a project I'd like to use

So being able to push / pull changes, idk. I have no idea how to use git, there's some tutorials that state cloning and creating your own repository and making a pull request from there when you've done changes.

Literally as I stated. I need a guide that explains how to properly clone a project so you can push and pull any changes you've made and make pull requests.

**Comment by chriskonnertz** [comment]
> The intention is to take an approach at learning some PHP while trying to contribute to a project I'd like to use
> 
> So being able to push / pull changes, idk. I have no idea how to use git, there's some tutorials that state cloning and creating your own repository and making a pull request from there when you've done changes.
> 

Ok, so the big question is: do you want to push directly to the original Contentify repository or do you want to push to your own fork (copy) of the Contentify repository?

Only the latter will work, because pushing directly to the original Contentify repository is not allowed. After pushing to your own repository you could create a cross repostitory pull request from you repository to the original repository.

> I need a guide that explains how to properly clone a project so you can push and pull any changes you've made and make pull requests.

1. Fork the original repository
2. Clone your forked repo: Type "git clone <repo-uri>" in a console window, e. g. "git clone https://github.com/Contentify/Contentify.git" (this URI is hidden behind the green "Clone or Download" button on th repo page)
3. Make some changes on your local repo copy
4. Commit them, for example via "git commit -all" (add new files to git via "git add --all")
5. Push them with "git push"
6. Create a new pull request here: https://github.com/Contentify/Contentify/compare (click on "compare accross forks")

You do not have to control git via console, there is also a number of graphical git clients. For example SourceTree ( https://www.sourcetreeapp.com/ ) and GitHub Desktop ( https://desktop.github.com/ )
