### ISSUE TITLE
Installing Error.

### ISSUE THREAD

**Issue by abdulsami34** [Contentify/Contentify#431]
Access denied for user 'root'@'localhost'  (SQL: SHOW TABLES LIKE "migrations")

**Comment by kamohy** [comment]
#380 can help :-)

**Comment by chriskonnertz** [comment]
@abdulsami34 I close this issue now, please create a new issue if the problem still exists.

**Comment by chriskonnertz** [comment]
PS: I faced the same issue today. If you have SSH access (terminal access) you should try this command:
`mysql -h localhost -u root -p`
When you press enter, you will have to copy+paste the MySQL password. Use the same password as in `app/storage/database.ini`. If the command prints the message "access denied" then _this is not a problem of Contentify but of MySQL_ - something went wrong with the user.  In general it makes sense to create a custom MySQL user (instead of `root`) to avoid such problems. Here is a tutorial: https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql
