### ISSUE TITLE
Cup join and some issues

### ISSUE THREAD

**Issue by abdulsami34** [Contentify/Contentify#436]
Hello there, 

I have created a cup. I started the cup but i can't join it. First it says you have no team okay then i created a team set its password and image. Now i have a team. But whenvever i click on join cup
It give me two options

My teams 
Team: Create new.
![untitled](https://user-images.githubusercontent.com/10799390/46922975-8f871a80-d02a-11e8-9ab1-3da71d993087.png)

After than i'm on a page showing my team name and then nothing else.

I needed to ask, If someone creates a team does it not show in Teams section. 
I have setup a team password is there any way to invite a member to my team because i can't see one.

**Comment by chriskonnertz** [comment]
Hello,

first, thank you for creating this issue. It provided very useful feedback!

I assume the problem here is not an actual **bug**, but it is bad design / bad user experience. I believe that what is happening is that there is only one member (player) in the team, which is you. But since this is a **team** cup there needs to be more than just one member (player) in the team! So someone else has to join your team, then you can let this team join the cup.

I made a change to improve user experience by showing the team name but disabling it and displaying a hint why you cannot use it: https://github.com/Contentify/Contentify/commit/b23e69f0f86de6ef159604d72ad86937f03d4620#diff-b696182cb223a944153d29e96357c9ad

**Comment by chriskonnertz** [comment]
> I have setup a team password is there any way to invite a member to my team because i can't see one.

If some one else creates a team, he/she would give you a link to the team, then you will see an "Join team" button. If you click it you would have to enter the password of the team, so the other person would have to tell you this password.

**Comment by abdulsami34** [comment]
Great to hear that. 
So, When ever there are more players in my team It will automatically show as : 
Team - Name etc?

By the way, I have succesfully installed contentify on a cpanel server and i have fixed the migration error very easily.

The solution was to that just to change a line in config/database.php 

//'host'      => env('DB_HOST', '127.0.0.1'), to //'host'      => env('DB_HOST', 'localhost'),

I tried the same on many other vps i own from other different companies. DigitalOcean - ArubaCloud and many others. 

I hope it will help anyone installing this!

**Comment by chriskonnertz** [comment]
> So, When ever there are more players in my team It will automatically show as :
Team - Name etc?

Yes.

**Comment by chriskonnertz** [comment]
> The solution was to that just to change a line in config/database.php
> 
> //'host' => env('DB_HOST', '127.0.0.1'), to //'host' => env('DB_HOST', 'localhost'),
> 
> I tried the same on many other vps i own from other different companies. DigitalOcean - ArubaCloud > and many others.

So do you recommend to permanently change it from "127.0.0.1" to "localhost"?

**Comment by abdulsami34** [comment]
Yeah.
I tried multiple times installing this and worked pretty well with this change.

**Comment by chriskonnertz** [comment]
Ok thanks.
