### ISSUE TITLE
Changing Theme Background Color

### ISSUE THREAD

**Issue by katzcentrality** [Contentify/Contentify#495]
Hi, it seems like the two themes included with Contentify have dark black backgrounds, and I can't figure out how to change the background color. I'm not too well-versed in PHP, so I'm not sure if it's something specific to the themes, or to the CMS itself. Thanks.

**Comment by chriskonnertz** [comment]
Hi,

yes, both themes have a dark background.


The body background color is set here: https://github.com/Contentify/Contentify/blob/v2.6/app/Modules/MorpheusTheme/Resources/Assets/less/frontend.less#L719

So this is LESS code, so you have to compile it, which is possible since v2.5(?) in the admin backend -> settings -> click on the "Compile LESS" button.

Since Contentify 2.6 you can also add custom LESS/CSS code in the admin backend-> settings page so you could add `body { background-color: white }` there. Compile LESS afterwards.

**Comment by katzcentrality** [comment]
Thank you so much!
