### ISSUE TITLE
[Question] Future translations?

### ISSUE THREAD

**Issue by torriz** [Contentify/Contentify#496]
Is there any plans of continuing translation further through "crowdin" (paid) or other FREE service?

I think it's better if the "main" project has these translations, rather than translating it 10 times for different projects by users of contentify.

Looking to get languages like:
Turkish, Bosnian, Croatian, Serbian, Dutch, Italian

**Comment by chriskonnertz** [comment]
Hi,

thank your for your feedback / question.

> I think it's better if the "main" project has these translations, rather than translating it 10 times for different projects by users of contentify.

I agree. That's why I have a great interest in incorporating translations.

But what I hate is unfinished stuff. I don't want to see a website that is 90% translated to my fluent language, but 10% not translated. That's why the current policy is: Every language that is officially integrated into Contentify has to be fully translated. 100%. No exceptions.

When I think of crowd translations, well, in all honest this is almost a synonym for unfinished translations.

Therefore the current strategy is to only officially support a small number of languages, but to support them 100%. I agree that Italian should be officially supported, but I am not sure about the other ones, because once they have been integrated, who is going to maintain these translations?

At this point, Crowdin seems to be too expensive. Do you have any other recommendations for free or less expensive alternatives? :)

**Comment by torriz** [comment]
Yeah, I agree, too expensive. 
It shouldn't cost anything, that would be much better for a project like this.

I don't have one in mind, but I'll post here if I come across one.

**Comment by torriz** [comment]
Hi @chriskonnertz got this mail from Crowdin:

``
As we mentioned, our team loves Open Source so much that we offer a completely free license for such project types!

All you need is to ask your PM to fill the following request: https://crowdin.com/page/open-source-project-setup-request

Once it's submitted, we will review it and approve if everything fits our requirements.``


In case you're interested :D

**Comment by torriz** [comment]
And I guess laravel has translated a lot of the strings we use too

**Comment by chriskonnertz** [comment]
Hi,

thank you, great tip! :+1: 

Unfortunately we cannot meet their requirements:

> You do not have Commercial products related to the Open Source project you are requesting a license for.

Right now we do not violate this rule, but this might change in the future. Contentify is and always will be 100% free open source. However, additional services or software etc. that is not free might be added to enhance the eco-system. Actually this is in the pipleline.

**Comment by torriz** [comment]
What are you looking to add? 

And that can change in the future, as you said. It doesn't violate it now so.. ;p

**Comment by chriskonnertz** [comment]
> What are you looking to add?

Just addiotional services .... support, installation, coding...

> And that can change in the future, as you said. It doesn't violate it now so.. ;p

In the **_near_** future and it is almost certain that it will happen.

**Comment by torriz** [comment]
Alright.. well, rip :D
