### ISSUE TITLE
Install failed - ErrorException / escapeshellarg

### ISSUE THREAD

**Issue by tsoparlan** [Contentify/Contentify#50]
Hellows! 
I've wanted to try out your CMS but i got stucked during installation. The only requirement that i didn't met was fileinfo extension. I'm using a shared hosting plan, thus i don't have acces to any php ini settings/extensions . I could try to contact my hosting support but are we sure that fileinfo extension is the 'culprit' here ?
Req : 
http://i.imgur.com/sM1XTh4.png

Full error message :
http://i.imgur.com/YpAtQ7H.png

    Whoops, looks like something went wrong.

    ErrorException in ProcessUtils.php line 74:
    escapeshellarg() has been disabled for security reasons
    in ProcessUtils.php line 74

**Comment by chriskonnertz** [comment]
> I could try to contact my hosting support but are we sure that fileinfo extension is the 'culprit' here ?

I don't know for sure. The script that causes the trouble is part of a Symfony component. This component is used by the underlying Framework Laravel. So with other words: This is way beyond my horizon. _escapeshellarg_ is a nativ PHP method. Hosters sometimes disable PHP features that allow access to the server (via the _exec_ command for example). So I assume this has nothing to do with the _fileinfo_ extension.

Maybe you should ask your hoster to allow access to this command since it's not an "evil" command: http://php.net/manual/de/function.escapeshellarg.php "Escape a string to be used as a shell argument" Escaping is **not ** dangerous. :)

**Comment by creativewild** [comment]
Hello,

I've found an article where it's written about increasing tax on goods and services, you may find more information here <http://frafradaphi.careymcconnell.com/aetjstkd>

All best, luisgomes@creativewild.net

**Comment by creativewild** [comment]
Hi,

I've found an interesting web site with different life stories, they are really cool, you may read more here <http://preshiquapo.bitsolid.net/aeebkusf>

Looking forward, luisgomes@creativewild.net
