### ISSUE TITLE
[Question] Use widgets in "Custom Pages", "Custom Content" and "News" articles?

### ISSUE THREAD

**Issue by torriz** [Contentify/Contentify#505]
Q1: Let's say I want to create a news article and include a Poll in the article itself.. Is this possibru somehow?

**Comment by chriskonnertz** [comment]
No, this is not possible out-of-the-box.

In general there are three obvious solutions:

1. Implement the possibility to use "codes" in the news, for example : `Please vote now: [poll id=123]` This would then display the polls widget for the poll with the ID 123. This is what WordPress does: https://codex.wordpress.org/Shortcode_API 
2. Somehow extend the CKEditor to allow including widgets. This could result in codes as well but with an interface to add them rather than just typing them as text. 
3. Build a new editor that composes an article from "blocks". One type of block could be a widget. WordPress has recently introcuded something similar with their Gutenberg Editor: https://wordpress.org/gutenberg/

The long-term plan is to implement the third option. But this is a huge new feature so it is not coming too soon.

So if you need a quick solution implementing the first option would be the way to go. It can be done without much effort if one [keeps it simple](https://en.wikipedia.org/wiki/KISS_principle)...

**Comment by torriz** [comment]
Yes to the 3rd option!

The "CKEditor" is kind of limiting the possibilities of article writing and page creation right now, so that would be great.

EDIT: Thanks for the in depth answer... way more than expected

**Comment by torriz** [comment]
nooo.. rip?
