### ISSUE TITLE
[Suggestion] News images

### ISSUE THREAD

**Issue by reneb71** [Contentify/Contentify#538]
Instead of having news images set by `Categories` let them be set `Manually` (Example from images or manually uploaded)

**Comment by reneb71** [comment]
to be honest, lot of things could be manually set to make things easier. Like opponents etc. Worst case scenario you have 100 opponents to scroll trought

**Comment by chriskonnertz** [comment]
Hello

> Instead of having news images set by Categories let them be set Manually

Thank you for your suggestion. I totally agree. But you are a little bit too late - this has been implemented a week ago! :D => https://github.com/Contentify/Contentify/pull/520 (It's in v3.0 though, not in v2.6).

> to be honest, lot of things could be manually set to make things easier. Like opponents etc. Worst case scenario you have 100 opponents to scroll trought

I am not sure if I understand what you are talking about. Please can you write a little bit more so I understand the scenario? Where are you (on which page)? Maybe post the (relative) URL? Which form element do you describe (with the 100 entries)?

**Comment by reneb71** [comment]
> Hello
> 
> > Instead of having news images set by Categories let them be set Manually
> 
> Thank you for your suggestion. I totally agree. But you are a little bit too late - this has been implemented a week ago! :D => #520 (It's in v3.0 though, not in v2.6).
> 
Allright. Cant wait for 3.0 to go live.

> > to be honest, lot of things could be manually set to make things easier. Like opponents etc. Worst case scenario you have 100 opponents to scroll trought
> 
> I am not sure if I understand what you are talking about. Please can you write a little bit more so I understand the scenario? Where are you (on which page)? Maybe post the (relative) URL? Which form element do you describe (with the 100 entries)?

This: https://i.imgur.com/isXeboz.png, opponents vary and its pain in the ass to go trought 2 stages

**Comment by chriskonnertz** [comment]
It's an unofficial standard to implement it this way (foreign teams being a separate model instead of just a name) in esports related content management system. This is they way to go for many years. We haven't implemented anything further in Contentify, but it alllows to add more features related to (foreign) teams: For example, you could have an overview page with all (foreign) teams. If you would click on the name of one team a new page would open with statistics, especially how many times the teams of your organization played against this team and how well they did. This would be easy to implement in Contentify, because you have all necessary data already. Of course this is an advanced feature that is not essential for a typical esports organisation website. Contentify has been developed with content-focused websites in mind and also for websites of big esports organisations. Sometimes this makes things a bit more complicated. Every coin has two sides...

_However_:

- You do not have to scroll, you can enter the (beginning of) the name of a team to find it quickly
- We could add a search text field to make it easier to find teams ( Example: https://selectize.github.io/selectize.js/#demo-single-item-select )
- We could add a text field as an alternative way to quickly enter the name of a team without having to create it first. The team would then be created automatically. But I do not like this idea.
- We could add a "create new team" button. If you click it, a popup (modal dialogue) would appear where you can create a new team. It would be saved via AJAX (thus the websites does not need to be reloaded so you do not lose any form input) and the new team would automatically be selected in the dropdown element. I don't like that either, it's annoying to implement and you kinda have to add logic twice. Plus if you add it here, you would have to add it in many other places as well (for consistency reasons).
