### ISSUE TITLE
ToDo Check admin permission in cups module

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#541]
It is not clear if the permission checking works correctly in the admin pages of the cups module.

Something like this seems to be missing:
```php
if (! $this->checkAccessUpdate()) {
    return null;
}
```

**Comment by chriskonnertz** [comment]
Removed "critical" label, because this (potential) bug is (or _might_ be) annoying but not a critical security issue. It's not really _critical_ if users with backend access can start the seeding of a cup even if they do not have the "update cups" right.

**Comment by BlueStormNetwork** [comment]
according to what you say i may need 3 users or 4 just for one task each with a permission create/update delete / read since i am super admin user and still have access denied issues just to create a country ie: international let say i can't...is there a way to grant access read/write/update or all to a profile so i can work on backend easily?

**Comment by chriskonnertz** [comment]
You cann edit the database to assign roles. There is a table `user_role` that assigns roles to users and well ofcourse a table `roles` that contains the roles.
