### ISSUE TITLE
[Suggestion] Add support to run 'composer install' inside install.php

### ISSUE THREAD

**Issue by funtimeerror** [Contentify/Contentify#545]
What if we added support inside the install script as part of the check to see if the vendor folder exists, that if it doesnt, lets the user run the composer install as part of the install process via the web browser.

see https://stackoverflow.com/questions/17219436/run-composer-with-a-php-script-in-browser as an example for running composer inside a php web script

**Comment by chriskonnertz** [comment]
In most cases this would not work on environments (hi  @ shared hosting) where the PHP script execution time is limited to 30 seconds.

Do you agree?

**Comment by funtimeerror** [comment]
been so long since I had to endure shared hosting that I almost forgot about all that pain lol.
hmmm.... what if I adjusted the travis-ci build job for when a release tag is created, it will do the install, then zip and re-upload back to github as a release attachment?

**Comment by chriskonnertz** [comment]
> been so long since I had to endure shared hosting that I almost forgot about all that pain lol.

Yeah shared hosting is nothing else than pure pain. 

>  what if I adjusted the travis-ci build job for when a release tag is created, it will do the install, then zip and re-upload back to github as a release attachment?

Hm cool idea from a technical point of view, but would be the advantage? Every release contains a "production-ready" upload of Contentify that includes that vendor folder. That has been an importart part of releasing ever since (or at least since v1.0, alpha/betas/rcs are excluded). Since  I want to have a "combined" upload adding it as a separte attachment would be a step back in my opinion. So even though it is interesting, I don't think it helps in this case.

However: it might be a way to automatically create this "production-ready" upload... So, hypothetically, your suggestion can be realised? Travis supports doing things only on when a new tag (or a release) is created? And it's possible to upload attachments to a new release? (I assume it is somehow possible to script that but is it possible in a clean way? Mybe even in an "official" way?)

**Comment by funtimeerror** [comment]
yea, Travis supports doing things 'on tag' so that when a tag is added, it can do a custom action like that.

see https://docs-staging.travis-ci.com/user/deployment/releases/ for examples and such.

The workflow i see would be as follows.

1) release commit is determined
2) a tag on the commit is created
3) travis-ci builds against that commit (due to new tag) and then uploads the release back into github.

also when setting up the oauth token side, either use the travis-ci client to encrypt the token, or use the environment variables area in the travis-ci section with the (do not show value in log) or use both! :)

**Comment by chriskonnertz** [comment]
Awesome! I will try to experiment with this at the weekend. It would be super cool to automate the release build process.

**Comment by chriskonnertz** [comment]
Just for your information: Because of https://github.com/Contentify/Contentify/issues/547 I don't want to put too much effort in improving the installation.

**Comment by torriz** [comment]
Is this timesaving in the long run?

**Comment by chriskonnertz** [comment]
I assume it is, yes.
